services:

    ibisit\AdminLTEBundle\Twig\RuntimeExtension:
        class: ibisit\AdminLTEBundle\Twig\RuntimeExtension
        arguments:
            - '@admin_lte_theme.context_helper'
            - '%admin_lte_theme.routes%'
        tags:
            - { name: twig.runtime }

    ibisit\AdminLTEBundle\Twig\EventsExtension:
        class: ibisit\AdminLTEBundle\Twig\EventsExtension
        arguments:
            - '@event_dispatcher'
            - '@admin_lte_theme.context_helper'
        tags:
            - { name: twig.runtime }

    ibisit\AdminLTEBundle\Twig\AdminExtension:
        class: ibisit\AdminLTEBundle\Twig\AdminExtension
        tags:
            - { name: twig.extension }

    admin_lte_theme.context_helper:
        class: ibisit\AdminLTEBundle\Helper\ContextHelper
        arguments:
            - '%admin_lte_theme.options%'

    ibisit\AdminLTEBundle\Helper\ContextHelper:
        alias: admin_lte_theme.context_helper
