services:

    ibisit\AdminLTEBundle\Menu\MenuBuilder:
        class: ibisit\AdminLTEBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@event_dispatcher"
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: adminlte_main }